export const bca2PdfStudents = [
  { roll: 1, name: "RAHUL KUMAR", father: "JANARDAN PRASAD", attended: 1, percent: 1 },
  { roll: 2, name: "HARSH KUMAR", father: "JITENDRA KUMAR SINGH", attended: 17, percent: 13 },
  { roll: 3, name: "ADITYA RAJ", father: "JITENDRA SAW", attended: 94, percent: 71 },
  { roll: 4, name: "ROHIT KUMAR", father: "JITENDRA MALAKAR", attended: 100, percent: 76 },
  { roll: 5, name: "RAVI RANJAN", father: "RAKESH SINGH", attended: 27, percent: 20 },
  { roll: 6, name: "ANKUSH RAJ", father: "MADHUSUDAN PRASAD", attended: 8, percent: 6 },
  { roll: 7, name: "HANS RAJ", father: "SHANKAR KUMAR", attended: 99, percent: 75 },
  { roll: 8, name: "KUNAL KRISHN", father: "SHASHI BHUSHAN PRASAD", attended: 8, percent: 6 },
  { roll: 9, name: "RAVI RANJAN KUMAR", father: "UPENDRA PRASAD", attended: 63, percent: 48 },
  { roll: 10, name: "KUNDAN KUMAR", father: "RAJESH RAM", attended: 97, percent: 73 },
  { roll: 11, name: "PRAGYA SUMAN", father: "PRAMOD PRASAD", attended: 71, percent: 54 },
  { roll: 12, name: "ABHAY KUMAR", father: "MANOJ KUMAR", attended: 8, percent: 6 },
  { roll: 13, name: "TANVIR ALAM", father: "MD SARWAR ALAM", attended: 10, percent: 8 },
  { roll: 14, name: "MD HASAN REZA", father: "MD ILIYAS ALAM", attended: 25, percent: 19 },
  { roll: 15, name: "AMARJEET RAJ", father: "PRATAP SINGH", attended: 103, percent: 78 },
  { roll: 16, name: "NUPUR KUMARI SINHA", father: "PRATAP KUMAR SINHA", attended: 55, percent: 42 },
  { roll: 17, name: "RIYA BHARTI", father: "SANJEET KUMAR", attended: 63, percent: 48 },
  { roll: 18, name: "RICHA KUMARI", father: "SANTOSH KUMAR", attended: 75, percent: 57 },
  { roll: 19, name: "DOLLY KUMARI", father: "MUNNA PRASAD GUPTA", attended: 60, percent: 45 },
  { roll: 20, name: "SHILPI KUMARI", father: "SURAJ KUMAR", attended: 42, percent: 32 },
  { roll: 21, name: "PRINCE KUMAR", father: "MUNNA KUMAR", attended: 54, percent: 41 },
  { roll: 22, name: "RAJEEV KUMAR", father: "DEVENDRA PRASAD", attended: 8, percent: 6 },
  { roll: 23, name: "ANJAY KUMAR", father: "AJAY KUMAR", attended: 16, percent: 12 },
  { roll: 24, name: "JEET GUPTA", father: "UMESH KUMAR", attended: 78, percent: 59 },
  { roll: 25, name: "SHIVAM KUMAR", father: "MAHESH RAM", attended: 15, percent: 11 },
  { roll: 26, name: "MUKESH KUMAR", father: "UMESH PRASAD", attended: 74, percent: 56 },
  { roll: 27, name: "AMAN KUMAR", father: "SANJAY KUMAR", attended: 49, percent: 37 },
  { roll: 28, name: "MAYANK SHARMA", father: "SHAILENDRA KUMAR", attended: 0, percent: 0 },
  { roll: 29, name: "ROCKY KUMAR", father: "DHARMENDRA PRASAD", attended: 11, percent: 8 },
  { roll: 30, name: "KUMARI NEHA BHARTI", father: "VINOD PRASAD", attended: 38, percent: 29 },
  { roll: 31, name: "SATYAM KUMAR", father: "MANOJ KUMAR", attended: 91, percent: 69 },
  { roll: 32, name: "SAHIL KUMAR", father: "DHARMENDRA KUMAR", attended: 57, percent: 43 },
  { roll: 33, name: "ABHINANDAN KUMAR", father: "MUNNA KUMAR", attended: 83, percent: 63 },
  { roll: 34, name: "SANIA SINHA", father: "RAKESHWAR KUMAR", attended: 52, percent: 39 },
  { roll: 35, name: "STUDENT 35", father: "N/A", attended: 0, percent: 0 },
  { roll: 36, name: "ABHISHEK KUMAR", father: "ANIL KUMAR", attended: 20, percent: 15 },
  { roll: 37, name: "GAUTAM KUMAR", father: "SANJAY SAW", attended: 1, percent: 1 },
  { roll: 38, name: "SUBHAM KUMAR", father: "MAHENDRA RAM", attended: 4, percent: 3 },
  { roll: 39, name: "AYUSH KUMAR", father: "AKHILESH SINGH", attended: 3, percent: 2 },
  { roll: 40, name: "SONALI KUMARI", father: "VINAY KUMAR", attended: 55, percent: 42 },
  { roll: 41, name: "AVINASH KUMAR", father: "PRADEEP PRASAD", attended: 1, percent: 1 },
  { roll: 42, name: "VISHAL KUMAR", father: "KISHOR KUMAR SINGH", attended: 78, percent: 59 },
  { roll: 43, name: "ABHISHEK KUMAR", father: "AKALESH KUMAR", attended: 59, percent: 45 },
  { roll: 44, name: "VARSHA RANI", father: "KAMLESH KUMAR", attended: 56, percent: 42 },
  { roll: 45, name: "RAGINI PRAJAPATI", father: "RAVINDAR KUMAR", attended: 91, percent: 69 },
  { roll: 46, name: "KASTURI KUMARI", father: "BHOLA KUMAR", attended: 98, percent: 74 },
  { roll: 47, name: "ADITYA KUMAR", father: "NAVIN KUMAR", attended: 5, percent: 4 },
  { roll: 48, name: "VIKASH KUMAR", father: "LALKESHWAR MOCHI", attended: 108, percent: 82 },
  { roll: 49, name: "SWETA RAJ", father: "RAJNISH SINGH", attended: 0, percent: 0 },
  { roll: 50, name: "PRAKASH RANJAN", father: "RAJ KUMAR PRASAD", attended: 35, percent: 27 },
  { roll: 51, name: "SHIVRAJ KUMAR", father: "BRAJESH KUMAR", attended: 110, percent: 83 },
  { roll: 52, name: "SHUBHAM KUMAR", father: "DILIP SAW", attended: 15, percent: 11 },
  { roll: 53, name: "IQRA ADIL", father: "MD ADIL JAFRI", attended: 0, percent: 0 },
  { roll: 54, name: "RISHAV RAJ", father: "AJIT KUMAR SINGH", attended: 0, percent: 0 },
  { roll: 55, name: "NITISH KUMAR", father: "SATISH KUMAR", attended: 18, percent: 14 },
  { roll: 56, name: "ANJALI KUMARI", father: "ANUP KUMAR", attended: 58, percent: 44 },
  { roll: 57, name: "SITTU KUMAR", father: "PAPPU MALAKAR", attended: 34, percent: 26 },
  { roll: 58, name: "SHUBHAM KUMAR", father: "PRAVIN KUMAR", attended: 2, percent: 2 },
  { roll: 59, name: "SAURAV KUMAR", father: "JAYPATI PRASAD", attended: 108, percent: 82 },
  { roll: 60, name: "KARAN ARJUN", father: "RAJKUMAR PAL", attended: 0, percent: 0 },
  { roll: 61, name: "PRASHANT KUMAR VERMA", father: "SANJAY PRASAD", attended: 3, percent: 2 },
  { roll: 62, name: "VIKASH KUMAR", father: "DINESH CHAUDHARI", attended: 4, percent: 3 },
  { roll: 63, name: "SHEEN ALIA", father: "MOHAMMED TARIQUE HUSSAIN", attended: 9, percent: 7 },
  { roll: 64, name: "YUVRAJ KUMAR", father: "GOPAL SINGH", attended: 0, percent: 0 },
  { roll: 65, name: "PIYUSH KUMAR", father: "DHARMENDRA KUMAR", attended: 128, percent: 97 },
  { roll: 66, name: "SHREYA BHARTI", father: "KUMAR AMRENDAR SINHA", attended: 3, percent: 2 },
  { roll: 67, name: "AMIT PRAKASH", father: "MUNDRIKA PRASAD", attended: 96, percent: 73 },
  { roll: 68, name: "RITU NANDA KUMARI", father: "SUDHIR KUMAR SINHA", attended: 0, percent: 0 },
  { roll: 69, name: "SHIVAM KUMAR", father: "SHANKAR KUMAR", attended: 17, percent: 13 },
  { roll: 70, name: "MONU KUMAR", father: "AYODHYA PRASAD", attended: 20, percent: 15 },
  { roll: 71, name: "RAVI RANJAN KUMAR", father: "DHARMENDRA KUMAR", attended: 30, percent: 23 },
  { roll: 72, name: "VIBHANSHU SHEKHAR", father: "PRAVIN KUMAR", attended: 15, percent: 11 },
  { roll: 73, name: "PREM KUMAR", father: "RANJIT KUMAR", attended: 53, percent: 40 },
  { roll: 74, name: "ADITYA KUMAR", father: "MITHLESH KUMAR", attended: 1, percent: 1 },
  { roll: 75, name: "ANKIT KUMAR", father: "NAGENDRA PRASAD", attended: 18, percent: 14 },
  { roll: 76, name: "SUDHANSHU KUMAR", father: "SUVESH KUMAR", attended: 72, percent: 55 },
  { roll: 77, name: "MD KAIF KHAN", father: "MD JAMAL KHAN", attended: 95, percent: 72 },
  { roll: 78, name: "ARWAZ KHAN", father: "MD AMIR KHAN", attended: 1, percent: 1 },
  { roll: 79, name: "ABHAY KUMAR", father: "RANJIT KUMAR SINGH", attended: 111, percent: 84 },
  { roll: 80, name: "ABHISHEK KUMAR", father: "RAJESH GUPTA", attended: 23, percent: 17 },
  { roll: 81, name: "DEVANSHU PANDEY", father: "JITU PANDEY", attended: 43, percent: 33 },
  { roll: 82, name: "MD SAKLAIN MUSTAK", father: "MD FIRDOUS ALAM", attended: 0, percent: 0 },
  { roll: 83, name: "KRISH KUMAR", father: "RAJU SINGH", attended: 1, percent: 1 },
  { roll: 84, name: "KANHAIYA KUMAR", father: "AKHILESH KUMAR", attended: 0, percent: 0 },
  { roll: 85, name: "MILI KUMARI", father: "SUDHIR KUMAR", attended: 0, percent: 0 },
  { roll: 86, name: "DEEPAK KUMAR", father: "SURESH YADAV", attended: 28, percent: 21 },
  { roll: 87, name: "VIJAY KUMAR", father: "KRISHANNADAN PRASAD", attended: 1, percent: 1 },
  { roll: 88, name: "ABHINAB DEV", father: "AKHILESH KUMAR", attended: 0, percent: 0 },
  { roll: 89, name: "AMIT KUMAR", father: "AMAR RANJAN SINGH", attended: 0, percent: 0 },
  { roll: 90, name: "GAURAV KUMAR", father: "ARVIND KUMAR SINGH", attended: 0, percent: 0 },
  { roll: 91, name: "AJIT KUMAR", father: "BHARAT YADAV", attended: 10, percent: 8 },
  { roll: 92, name: "RITIK RAJ", father: "BIPIN KUMAR", attended: 56, percent: 42 },
  { roll: 93, name: "SONAL ANAND", father: "DINESH KUMAR AMBEDKAR", attended: 114, percent: 86 },
  { roll: 94, name: "RAVI RAJ", father: "SATYENDRA KUMAR", attended: 2, percent: 2 },
  { roll: 95, name: "RUDRA ABHISHEK", father: "SHRAVAN PRASAD GUPTA", attended: 0, percent: 0 },
  { roll: 96, name: "MD RASHID EQBAL", father: "MD MOJAHID EQBAL", attended: 2, percent: 2 },
  { roll: 97, name: "ABHISHEK KUMAR", father: "AKHILESH KUMAR", attended: 109, percent: 83 },
  { roll: 98, name: "STUDENT 98", father: "N/A", attended: 0, percent: 0 },
  { roll: 99, name: "SANJANA GUPTA", father: "GAUTAM GUPTA", attended: 69, percent: 52 },
  { roll: 100, name: "LAKSHMAN KUMAR", father: "SUDHIR PRASAD", attended: 3, percent: 2 }
];
